### ISSUE TITLE
Inventory Tracking

### ISSUE THREAD

**Issue by aroelke** [aroelke/mtg-workstation#129]
Add the ability to track individuals' inventories.  This could be stored in a regular `Deck` whose location is specified in the settings dialog. "Date Added" then becomes literal for the inventory, and the current use can be moved to a new "Date Released" attribute with a new filter.

**Comment by aroelke** [comment]
Additional ideas:
- [ ] "Date Added" becomes date first added to personal inventory and current use becomes "Date Released" with a new filter.
- [ ] Tags become categories in the inventory `Deck`.
- [ ] Foil copies can be tracked as a special `extra` list in the `Deck`.
